[tox]
envlist = py39,py310,py311,py312

[testenv]
deps =
    pytest
    requests
    flask
commands =
    pytest tests/test_scrape.py tests/test_server.py {posargs}

[testenv:e2e]
deps =
    pytest
    pytest-playwright
    requests
    flask
commands =
    playwright install chromium
    pytest tests/test_e2e_browser.py {posargs}

[testenv:format]
deps =
    black
    isort
    autoflake
commands =
    autoflake --remove-all-unused-imports --in-place --recursive .
    isort .
    black .

[testenv:format-check]
deps =
    black
    isort
commands =
    isort --check-only .
    black --check .
